services:
  neo4j-test1234:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_server_config_strict__validation_enabled: false
      KTHCLOUD_RAM: 1
      KTHCLOUD_CORES: 1
    ports:
      - "7687:7687"

    # Volumes kan tas bort om man inte vill ha persistent storage, då slipper man använda --try-volumes och de jobbiga med att sno cookies från browsern.
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  neo4j-browser:
    image: phillezi/neo4j-browser:latest
    environment:
      KTHCLOUD_RAM: 0.1
      KTHCLOUD_CORES: 0.1
    ports:
      - "8080:8080"

volumes:
  neo4j-data:
  neo4j-logs:
