services:
  neo4j-test123:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - "7474:7474"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  bolt-proxy-test321:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "7687:7687"
    depends_on: [neo4j-test123]

volumes:
  neo4j-data:
  neo4j-logs:
