services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "7687:7687"
    depends_on:
      - neo4j

volumes:
  neo4j-data:
  neo4j-logs:
